### ISSUE TITLE
Aprendamos Git

### ISSUE THREAD

**Issue by dwarlyndut** [marcelomazza/aprende-git#3]
Hola, Marcelo Mazza.
Excelente vamos aprender y generar un poco de experiencia real con esto!!

Feedback:  lo primero que diria de del README es que seria super encanchador hacer mención  a Git a Github en todos las,  yo en  particular inicio leyendo el aprendamos GIT perfecto, pero luego miro que vamos a crear una cuenta de github entonces instruyo que miramos los 2.
Quiza yo sepa y lo instruya, pero puede que alguien no!!
Entonces creeria que deberiamos ser mas claros.
Por otro lado siento que el titulo dice que solo se necesita saber leer y escribir y si esta claro y es eso, pero creo que llevarlo a un nivel un poco más alla seria estupendo.

Ver por ejemplo codigo sencillo de html y en ese sencillo codigo trabajar todo.
subir, borrar, unir, todo.
Si se me viene otra idea edito mi Isssues.

**Comment by marcelomazza** [comment]
@dwarlyndut gracias! Te pido que me clarifiques algunas partes de tu comentario que no entendí:

> hacer mención a Git a Github en todos las

¿Te referís a diferenciar lo que es Git de GitHub?

**Comment by dwarlyndut** [comment]
Ahh, ok.
En el README existen algunos textos que dicen aprende git, en ese sentido digo que es buena idea decir o escribir (aprender git y github) para mi es la manera de ser mas explicitos.
Cuando digo explicitos lo digo para que los que esten interesados puedan saber que se trabajara de forma local y en el repositorio real.

**Comment by marcelomazza** [comment]
@dwarlyndut entendí, gracias! Me parece bien.

¿Sabés lo que es un Pull Request?

**Comment by dwarlyndut** [comment]
La verdad si me hablas de conceptos los conozcos por que en un tiempo lo estudie, pero ahora no tengo claridad, podria leer y retomar el concepto.

**Comment by marcelomazza** [comment]
@dwarlyndut no hay problema. Te dejo un primer ejercicio, por favor chequear la resolución: https://github.com/marcelomazza/aprende-git/blob/main/ejercicios/fork.md

**Comment by dwarlyndut** [comment]
@marcelomazza  ya cree un fork 
https://github.com/dwarlyndut/aprende-git

**Comment by dwarlyndut** [comment]
Hola @marcelomazza muchas gracias!!

Realicé los pasos del siguiente ejercicio, en principio no me mostraba una información.
Creo que esta bien si no, pódrias darme feedback, estoy atento para seguir avanzando.

**Comment by marcelomazza** [comment]
@dwarlyndut está muy bien. Siempre es bueno dejar links, por ejemplo al Pull Request. Voy a cerrar este issue y abrir un nuevo issue con una tarea para vos.
