### ISSUE TITLE
Hola Marcelo! gracias por el curso de Git, a la espera de instrucciones.

### ISSUE THREAD

**Issue by LuisDevJava** [marcelomazza/aprende-git#5]
Hola Marcelo! gracias por el curso de Git, a la espera de instrucciones.

**Comment by marcelomazza** [comment]
Hola @LuisDevJava ! Ya está subido el primer ejercicio: https://github.com/marcelomazza/aprende-git/blob/main/ejercicios/fork.md preguntame cualquier duda. Fijate la resolución del mismo.

**Comment by LuisDevJava** [comment]
https://github.com/LuisDevJava/aprende-git

**Comment by marcelomazza** [comment]
Hola @LuisDevJava un éxito! Revisa el ejercicio 2 en https://github.com/marcelomazza/aprende-git/blob/main/ejercicios/pull-request.md
